apiVersion: v1
kind: Secret
metadata:
  name: formflow-backend-secrets
  namespace: formflow
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@host.minikube.internal:5432/formflow?schema=public"
  REDIS_URL: "redis://host.minikube.internal:6379"
  JWT_ACCESS_SECRET: "hdbfhbdhvbsfgfbiggibvhdbvisbfgvibff"
